apiVersion: v1
kind: Namespace
metadata:
  name: contacts
---
apiVersion: v1     
kind: Secret
metadata:
  name: tlscerts
  namespace: contacts
data:
  contacts-api.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lKQVBqUVBZYVF1Zm1RTUEwR0NTcUdTSWIzRFFFQkJRVUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOak13TVRnMU5EQTJXaGNOTXpFd016QTVNVGcxTkRBMgpXakFYTVJVd0V3WURWUVFEREF4amIyNTBZV04wY3kxaGNHa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRQ3ZySkNTSldXWGl0NFF1NVJHRXpGMkVtaDRXMFBEeG5SU2Y2QVQzdlN1VGJmd2RUUDMKaTBIWTd6d1RHYVg2bC9GMkpFVi9oMHNTOGhZY3JzakNNWVVtcG9OUnZDbGRGby9HdWZnK3U5ZVE0WG9xRlNWLwpCejNUU1pPVW1iUjAwWmdBWlJpejlpbE53TGliOHAzRVh0V1dvUy8zd21QTk5oamFiMHJYSXBvdG5KWWd4MmdOCkNINkw2M2x0ek1lOVJKWnpsWWp6S3dVb0s1Ykl5NURacndlMzR4UFZWcFNDQUZHaEZMTmk3eGZYRWkzUVZsNzAKUVJSOWVkMjFmL0tjSWUzNnFTaGd0MHhxOXNRbUpwa2ZaUE5RTlNXSWRFSGhGQ0NzU3VOWTFyRFh1ZEg0dVcycAplbEptSUdGL2xhNXozTFJqRDVuVnZLd2R5L2NCYTU1Ny8wM25BZ01CQUFHall6QmhNQWtHQTFVZEV3UUNNQUF3CkN3WURWUjBQQkFRREFnWGdNRWNHQTFVZEVRUkFNRDZDQTJGd2FZSU1ZWEJwTG1OdmJuUmhZM1J6Z2g1aGNHa3UKWTI5dWRHRmpkSE11YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDQ1d4dlkyRnNhRzl6ZERBTkJna3Foa2lHOXcwQgpBUVVGQUFPQ0FRRUFGQnpxcEJ1SzNEVmtBcmV5SVlyWjlsWkNSQ1hvOVgrcGVrWGI2aElyZ1RGdkFTODhTZ0NTCmhscytkWEJBMzZ4em04ckorMlc5S3RZYTNiRCtnVnVDVVljWjlGWHU5RHBObVpra2hUeG91MTNHMVRqU0RnZGgKNktjWXBwMXVrVldraU1wclJYSmNzZndraVVDNERzaVduV2tLRjJvTjVaNGNyNmVCaVNJWjZEQVBFWDVIeXdHWgpGZGNyc2E5dGdaMEV5a0Y0WjczT0NZaFA5a0ZrYnhjZmlKMVlmWUMxdG5rM0lTTDF1N2x0SVhYTUFzV1lzZXYvCjNVKzdqSW9IZ05OK0RjYm9YcGh5dDRpNjBHZWlOamRyRDF5cU9Nazl0Uis3MDFwRjBwWTZFN1RUSnNwai8xaS8KeGFoOFovWlA5aW1VWloydTdkMm5TTnJpZ2JOZnU0c3VsZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  contacts-api-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcjZ5UWtpVmxsNHJlRUx1VVJoTXhkaEpvZUZ0RHc4WjBVbitnRTk3MHJrMjM4SFV6Cjk0dEIyTzg4RXhtbCtwZnhkaVJGZjRkTEV2SVdISzdJd2pHRkpxYURVYndwWFJhUHhybjRQcnZYa09GNktoVWwKZndjOTAwbVRsSm0wZE5HWUFHVVlzL1lwVGNDNG0vS2R4RjdWbHFFdjk4Smp6VFlZMm05SzF5S2FMWnlXSU1kbwpEUWgraSt0NWJjekh2VVNXYzVXSTh5c0ZLQ3VXeU11UTJhOEh0K01UMVZhVWdnQlJvUlN6WXU4WDF4SXQwRlplCjlFRVVmWG5kdFgveW5DSHQrcWtvWUxkTWF2YkVKaWFaSDJUelVEVWxpSFJCNFJRZ3JFcmpXTmF3MTduUitMbHQKcVhwU1ppQmhmNVd1Yzl5MFl3K1oxYnlzSGN2M0FXdWVlLzlONXdJREFRQUJBb0lCQUVhZHIxK1ArTTU1MjlvTwpEUVErSXR1N2VwTW0zSTZONzZSWitSY0R3SWR3WmtnYVZORmxBUXNhMzZNdDVESmZjWWh6L0J2UFhyWTI2ZnlOCnBkV3A0a1F2R3dwNEFJaVMwU2lwQ01qdTZUQXI4dGVIdUpMZmJsTEllTEo3TnJiZXFhTS9BRGNXOUhOMHpNQ2oKUGhmNXB4SHRxVUtHdVdkOEgzRnUyejZ2Z2hwaTlOYTNyN2U2K0JNaFhLcW5sTWFjZGphaHJtTk5lSzMxcVdtZQpPc3lrOFUrd2RzNmk1ODdSZnV2QWpiQkc4WVRWaElWUENINWxYc05EY3FLclUwWFRvS0ZzR054MVFXTjlGMEJBCkcxUkp3YXZTSEtLNXlyQUZFQWNuY0FJeUI1MWpPMTdJQU81ajZEVEZWdDJOWk45Nmd3UWVUK1BCYzJEZWNxZlcKcWpJYUUwRUNnWUVBMWJvdk1Ed095RXZUWFpCMEp3eUZyQ0VGRjRIRnlHVC9RTG0rRUxoaFhyTkpQVlp2ZnllWgpaVWdGZmhNbm5yWXAvdWVKRWQxV2J2QVZuSjFzcTJrS2p1R1F6YkJZUHBramlCZVF1UHNHTS9tbXZXcUJzVHo1ClNGbWVVcDZ5TmU4aklRZEF1Qm9LOHhBZXRqVGE1SUZ3YUdQTi9vdkZGU3ZqakF3M1RWbEVqcXNDZ1lFQTBtdWEKa01IZUhhbjJodC9lMEVrSEZ1cGtqSExCM1pNUlhjTWFoSnh5YzVDc0h4MCtacnNaU0VPYnErK1JxTDh5UWNYYwpveXhremd5TnljZkovUm45NHpWRTRLRjJvVjA2bW1IYUdObWNwaGlQYWJQWXg3M1c1aktTaDhWbEpJdFpsR1NTCm1ZTHpGQ2QydGhIY0hiUThpalB6bUFEMHBOYUdnaEEreXNyWFRiVUNnWUVBcUFxalg0RlkvaExnTlFpR3lzMEYKckxpcGtEbndrQWNZeW9NLzlWV0MrVHB0czFScWhjZFV6RlU4UEV4RE1uNTN0bnZGUWM2TlR0eGxvYVlFOHlDNwp0R3VWdHFPWVBsK1ptRDh2QXNJYnRuSHJyN0kyRm15aWMwaERPeUtiYTl5QitrNEJqTDZ0TFQ3WFp0dFgzNklHCkI0MnhRUm9UOHZsM0IzM3pYVlY2bWRFQ2dZQXVsWTN4a0VvSlRUQjc2YUlkZ0oxbU1GdzBUOCtscTBLRC9JYXAKWnkxYmNtTDR2SE90TUt6SE45aUY5eExMUmhEdFNNMncva29PNSs2WUJuZ3NaWTIwdUgxWU1jYmVzSkloelpvSQpPRjBhMUlNamhxSnVqaE8rZ09HNTF6U3VJMytnZjZlSS90bXIwNVRQZUNMQUhML3VaTlFBQ2U0ZmRETHhKb0dRClNkbmlwUUtCZ0ZkWi8ra2JtdnhvSnUrR0pSS1BSSFZLRERwUytXT2xoMjhkZno5aTQzV1dFa3dYazNGTWZaV1gKS2FXc1Q4T3U5WGhXTHU5T1QzNU5LT3lsalJtNzFwdUZlZm12MmtyZEphS1MzaHZ6cmI3eVFCSmZVTFpQVzZOZgp4N3NMbndjbWUvdDVUeHo1bFNUeFRJTTVlcllEQUpyZ242TWFCaktWbitrTDNFWU5PRUZNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMRENDQWhTZ0F3SUJBZ0lKQU5HVWFRR0d2TVNlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmd4RmpBVUJnTlYKQkFNVERXNW5jQzF3Y21sdFpYSXRZMkV3SGhjTk1UY3dOak13TVRnMU5EQTJXaGNOTXpFd016QTVNVGcxTkRBMgpXakFZTVJZd0ZBWURWUVFERXcxdVozQXRjSEpwYldWeUxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFzaDR5TStkNmdCR0VUelhpcGswdEJTaGNZWUhNbVRLVUwrZm8rei9rZ3RrMlNYMlYKcFVXK0tVVUxITURLVUEralU1RWI2VHBSNjFBMmdYNDlRaWxIZ2VYMzdLU2E5QVVQU2srbUgzM3FscXZlQ2gvSwoxREt5L3hLZTdONmxoeDRwbVhRV3h2WGZOdWg1eGM0NVpNYW1BM010UzE5OXZGMk1DaWFNSmxMOTJNMmRNSVFMCi9hUTluMjJRYXRKcUNyYlJNZTJlSGQ5aGFnTXh4NmtvbGpCaU5ZUXpXOTQ4bytLa0xNelE2UWE5MElrcnhXb2oKZ3JEaXlidmFqT2VndWlOd3E0eTFCZ2FWSEVTVGE3eUVJYkhLU1RWck1COXFUc0Nva0RzR1p6VXlUU1JnZU45NgpLM2tkRzMrVUkwOWFraDkxVVZ6ckpzVjlXMUxvYU1vUkNmQXI0UUlEQVFBQm8za3dkekFkQmdOVkhRNEVGZ1FVCjVGcDBSL1ArM0QvZWE1Ym9HRU85OVE1VE9YY3dTQVlEVlIwakJFRXdQNEFVNUZwMFIvUCszRC9lYTVib0dFTzkKOVE1VE9YZWhIS1FhTUJneEZqQVVCZ05WQkFNVERXNW5jQzF3Y21sdFpYSXRZMkdDQ1FEUmxHa0JocnpFbmpBTQpCZ05WSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZE81aEVSRWViWjNKYjk0QzJkT2pxCkNoVmtycUl4OTgvYmFSOHppZTJXUmUzRU1YV2I3ei9rOUVGanhsRWxXQkhOL1FpdFZUZzhNeElNd0RFVGZ1TjkKcVBaRE85OE9GRXZZZWxwaTdlM0x3NVlQd2hBT1hBa2laUHFjQ0tZRlRvbFFod3kvQnpvRVpCbmdXK052VkNpWgp6My9XYmMvRmlwUmNwdGVFaUZEL2d3bUFoaFJnYlpjM0NaRHRhUmVBdWRqUjAwY3F2amlLU0d2N0dCMU4zT0xsClpvZEpTd3NBT2lDVGNBMHMwQ0FlNndHaWVOOFhBRnhiYlZhSWpkblRtNUFmWkdsZ0E2cVBjQTU0R1loVE5FTFoKZzlDODdYK2t0SDdLeEFSYndQV0RjcmJnMEI0bGFDYjE0RlRLWnYzVUQ5K2Nqb3p3QXREWXVTQUtKRWdxYnNLYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  replicas: 3
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: api-server
        image: johnbelamaric/contacts-api
        imagePullPolicy: Always
        args:
        - -dsn
        - api:mypassword@tcp(mysql.db:3306)/contacts?charset=utf8&parseTime=True
        - -s
        - :443
        - -cert
        - /etc/certs/contacts-api.pem
        - -key
        - /etc/certs/contacts-api-key.pem
        - -ca
        - /etc/certs/ca.pem
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts: 
        - name: tlscerts
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: tlscerts
        secret:
          secretName: tlscerts
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  type: NodePort
  selector:
    app: contacts
  ports:
  - name: https
    port: 443
    protocol: TCP
